[package]
name = "auction-mock"
version = "0.3.4"
authors = ["Team Dharitri <contact@dharitri.org>"]
edition = "2021"

[dependencies.node-storage]
path = "../node-storage"

[dependencies.dharitri-sc]
# version = "=2.0.0"
path = "/home/dharitri/Downloads/drt-rs-sdk-2.0.0/framework/base"
features = ["alloc"]

[dev-dependencies.dharitri-sc-scenario]
# version = "=2.0.0"
path = "/home/dharitri/Downloads/drt-rs-sdk-2.0.0/framework/scenario"
