[package]
name = "delegation_latest"
version = "1.0.0"
authors = ["Team Dharitri <contact@dharitri.org>"]
edition = "2021"

[lib]
path = "src/delegation_main.rs"

[dependencies.node-storage]
path = "../node-storage"

[dependencies.user-fund-storage]
path = "../user-fund-storage"

[dependencies.dharitri-sc-modules]
# version = "=2.0.0"
path = "/home/dharitri/Downloads/drt-rs-sdk-2.0.0/contracts/modules"

[dependencies.dharitri-sc]
# version = "=2.0.0"
path = "/home/dharitri/Downloads/drt-rs-sdk-2.0.0/framework/base"

[dev-dependencies.dharitri-sc-scenario]
# version = "=2.0.0"
path = "/home/dharitri/Downloads/drt-rs-sdk-2.0.0/framework/scenario"

[dev-dependencies.auction-mock]
path = "../auction-mock"
