name: CI

on:
  push:
    branches: [ main, dev]
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: TerraDharitri/drt-sc-actions/.github/workflows/contracts.yml@6f58cef408b010a78724c7941128310d2065adfa
    with:
      rust-toolchain: stable
      drt-go-scenario-version: v1.0.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
